// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251023193316_UpdateInviteTracking")]
    partial class UpdateInviteTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Models.InvitationToGame", b =>
                {
                    b.Property<string>("RoomKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username1")
                        .HasColumnType("TEXT");

                    b.HasKey("RoomKey");

                    b.HasIndex("Username");

                    b.HasIndex("Username1");

                    b.ToTable("InvitationToGame");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("FourInARowMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourInARowWinStreak")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Friends")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("IncomingFriendRequests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OutgoingFriendRequests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PairMatchingMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PairMatchingWinStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RockPaperScissorsMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RockPaperScissorsWinStreak")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.InvitationToGame", b =>
                {
                    b.HasOne("Models.User", null)
                        .WithMany("IncomingInviteToGameRequests")
                        .HasForeignKey("Username");

                    b.HasOne("Models.User", null)
                        .WithMany("OutcomingInviteToGameRequests")
                        .HasForeignKey("Username1");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Navigation("IncomingInviteToGameRequests");

                    b.Navigation("OutcomingInviteToGameRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
