// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250921201337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("FourInARowMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourInARowWinStreak")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Friends")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PairMatchingMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PairMatchingWinStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RockPaperScissorsMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RockPaperScissorsWinStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentWinStreak")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
