// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251023212743_AddOwnedInvitations")]
    partial class AddOwnedInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("FourInARowMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourInARowWinStreak")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Friends")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("IncomingFriendRequests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OutgoingFriendRequests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PairMatchingMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PairMatchingWinStreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RockPaperScissorsMMR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RockPaperScissorsWinStreak")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.OwnsMany("Models.FromInvitationToGame", "IncomingInviteToGameRequests", b1 =>
                        {
                            b1.Property<string>("Username")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("FromUsername")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoomKey")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Username", "__synthesizedOrdinal");

                            b1.ToTable("Users");

                            b1.ToJson("IncomingInviteToGameRequests");

                            b1.WithOwner()
                                .HasForeignKey("Username");
                        });

                    b.OwnsMany("Models.ToInvitationToGame", "OutcomingInviteToGameRequests", b1 =>
                        {
                            b1.Property<string>("Username")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("FromUsername")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoomKey")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Username", "__synthesizedOrdinal");

                            b1.ToTable("Users");

                            b1.ToJson("OutcomingInviteToGameRequests");

                            b1.WithOwner()
                                .HasForeignKey("Username");
                        });

                    b.Navigation("IncomingInviteToGameRequests");

                    b.Navigation("OutcomingInviteToGameRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
